_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "CUB"
  DATAPATH: "/workspace/CUB_200_2011"
  NUMBER_CLASSES: 2
  MULTILABEL: False
  ATTRIBUTE : 'small_(5_-_9_in)'
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01
  TOTAL_EPOCH: 50
  LOG_EVERY_N: 50