_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "CUB"
  DATAPATH: "/workspace/CUB_200_2011"
  NUMBER_CLASSES: 2
  MULTILABEL: False
  ATTRIBUTE: ""
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.01
  LOG_EVERY_N: 50
